.TH SHELL 1 "DECEMBER 16, 2024" "Holberton School Team Project" "Simple shell man page"

.SH NAME
.B simple_shell \- simple UNIX command interpreter made in C

.SH SYNOPSIS
C is not fun$ /hsh [options] [file]
.nf
#include "main.h"
.br
int main(int argc, char **argv);
.fi

.SH DESCRIPTION
The Shell, named Simple Shell, replicates basic functionalities of a Unix shell, including command execution, path searching. Simple Shell is a command language interpreter that executes commands read from the standard input, tokenize them, execute them in a child process, and handle errors. It also supports executing commands both with absolute paths and by searching the PATH environment variable.

.SH RETURN VALUE

Always returns the status of previously executed command (exit if not command executed).

.PP
The
.B read_line.c
Function to command invit and return void.

.B get_file.c

.B token.c

.B _free.c

.SH LIBRARY
#include <stdio.h>
.br
#include <stdlib.h>
.br
#include <unistd.h>
.br
#include <string.h>
.fi
#include <sys/types.h>
.br
#include <sys/stat.h>
.br
#include <sys/wait.h>
.br

.SH ENVIRONNEMENT
extern char **environ; 

.SH History
.B hsh
The Simple Shell is based on the Thompson Shell program written by Ken Thompson.

.SH BUGS
Today i know i hate betty style, we got to many memory leaks.

.SH AUTHORS
Julie TOLVE, Jordan BAROUX.
