.TH SHELL 1 "DECEMBER 16, 2024" "Holberton School Team Project" "Simple shell man page"

.SH NAME
.B simple_shell \- simple UNIX command interpreter made in C

.SH SYNOPSIS
C is not fun$ /hsh [options] [file]
.nf
#include "main.h"
.br
int main(int argc, char **argv);
.fi

.SH DESCRIPTION
The Shell, named Simple Shell, replicates basic functionalities of a Unix shell, including command execution, path searching. Simple Shell is a command language interpreter that executes commands read from the standard input, tokenize them, execute them in a child process, and handle errors. It also supports executing commands both with absolute paths and by searching the PATH environment variable.

.SH RETURN VALUE

Always returns the status of previously executed command (exit if not command executed).

.SH FILES

.B _getenv.c
.br
Environment function.
.br
char *_getenv(const char *name);

.B print_env.c
.br
Print environment variable.
.br
void print_env(void);

.B get_file.c
.br
Executable PATH of the file and environment.
.br
int slash(const char *str);
.br
char *get_path(char *file_name);

.B _error.c
.br
Print error message.
.br
int _error(void);

.B _free.c
.br
Free multiple buffer.
.br
void _free(char *buffer, char **array, char *path);

.B prompt.c
.br
Function create prompt simple shell.
.br
void prompt(void);

.B main.c
.br
Main function.
.br
int main (int argc, char **argv);
.br
void execute_command(char **array);

.B main.h
.br
Header file with pototypes functions and libraries.


.SH LIBRARY
#include <stdio.h>
.br
#include <stdlib.h>
.br
#include <unistd.h>
.br
#include <string.h>
.fi
#include <sys/types.h>
.br
#include <sys/stat.h>
.br
#include <sys/wait.h>
.br

.SH ENVIRONNEMENT
extern char **environ; 

.SH History
.B hsh
The Simple Shell is based on the Thompson Shell program written by Ken Thompson.

.SH BUGS
Inside the code take care about memory leaks. but it's work.

.SH AUTHORS
Julie TOLVE, Jordan BAROUX.
